baseURL = 'https://hayatehay.github.io/blog/'
languageCode = 'ja'
languageName = 'Japanese'
defaultContentLanguage = 'ja'
hasCJKLanguage = true
title = 'はやてにっき'
theme = 'ananke'
copyright = 'NAKA-MURA Hayate'

[markup.goldmark.renderer]
unsafe = true

[params]
text_color = 'dark-gray'
background_color_class = 'bg-navy'
author = 'NAKA-MURA Hayate'
favicon = '/blog/images/common/logo.png'
site_logo = '/blog/images/common/logo.png'

[[params.ananke_socials]]
name = 'Misskey'
url  = 'https://misskey.io/@hay_nh521'

[[params.ananke_socials]]
name = 'Mastodon'
url  = 'https://fedibird.com/@hayatehay'

[[params.ananke_socials]]
name = 'GitHub'
url  = 'https://github.com/hayatehay/'

[[params.ananke_socials]]
name = 'Instagram'
url  = 'https://instagram.com/hay_nh521/'

[[params.ananke_socials]]
name = 'ウェブサイトに戻る'
url  = 'https://hayatehay.github.io/'
